////********** AUTOGENERATED FILE: DO NOT REMOVE ANY COMMENT IN THIS STYLE **********////
////********** START IMPORTS **********////
import '../../../../../infrastructure/datasource.dart';
import '../../../domain/usecases/load_users_from_contacts.dart';
import '../../../domain/usecases/add_friend.dart';
import '../../../domain/usecases/get_founders_usecase.dart';
import '../../../domain/usecases/follow_user.dart';
import '../../../domain/usecases/unfollow_user.dart';
import '../../../domain/usecases/set_initial_invites_sent_usecase.dart';
import '../../../domain/usecases/get_recieved_friend_requests.dart';
import '../../../domain/usecases/accept_friend_request.dart';
import '../../../domain/usecases/get_all_friends.dart';
import '../../../domain/usecases/un_friend.dart';
import '../../../domain/usecases/get_close_friends.dart';
import '../../../domain/usecases/add_friend_to_close_friend.dart';
import '../../../domain/usecases/remove_friend_from_close_friends.dart';
import '../../../domain/usecases/cancel_friend_request.dart';
////********** END IMPORTS **********////

abstract class FriendsFirebaseDataSource extends DataSource {
  ////********** START METHODS **********////
  /// [LoadUsersFromContactsUsecaseInput] is received to [loadUsersFromContacts] method as parameter
  /// [LoadUsersFromContactsUsecaseOutput] is returned from [loadUsersFromContacts] method
  Future<LoadUsersFromContactsUsecaseOutput> loadUsersFromContacts(
      LoadUsersFromContactsUsecaseInput input);

  /// [AddFriendUsecaseInput] is received to [addFriend] method as parameter
  /// [AddFriendUsecaseOutput] is returned from [addFriend] method
  Future<AddFriendUsecaseOutput> addFriend(AddFriendUsecaseInput input);

  /// [GetFoundersUsecaseUsecaseInput] is received to [getFounders] method as parameter
  /// [GetFoundersUsecaseUsecaseOutput] is returned from [getFounders] method
  Future<GetFoundersUsecaseUsecaseOutput> getFounders(
      GetFoundersUsecaseUsecaseInput input);

  /// [FollowUserUsecaseInput] is received to [followUser] method as parameter
  /// [FollowUserUsecaseOutput] is returned from [followUser] method
  Future<FollowUserUsecaseOutput> followUser(FollowUserUsecaseInput input);

  /// [UnfollowUserUsecaseInput] is received to [unfollowUser] method as parameter
  /// [UnfollowUserUsecaseOutput] is returned from [unfollowUser] method
  Future<UnfollowUserUsecaseOutput> unfollowUser(
      UnfollowUserUsecaseInput input);

  /// [SetInitialInvitesSentUsecaseUsecaseInput] is received to [setInitialInvitesSent] method as parameter
  /// [SetInitialInvitesSentUsecaseUsecaseOutput] is returned from [setInitialInvitesSent] method
  Future<SetInitialInvitesSentUsecaseUsecaseOutput> setInitialInvitesSent(
      SetInitialInvitesSentUsecaseUsecaseInput input);

  /// [GetReceivedFriendRequestsUsecaseInput] is received to [getReceivedFriendRequests] method as parameter
  /// [GetReceivedFriendRequestsUsecaseOutput] is returned from [getReceivedFriendRequests] method
  GetReceivedFriendRequestsUsecaseOutput getReceivedFriendRequests(
      GetReceivedFriendRequestsUsecaseInput input);

  /// [AcceptFriendRequestUsecaseInput] is received to [acceptFriendRequest] method as parameter
  /// [AcceptFriendRequestUsecaseOutput] is returned from [acceptFriendRequest] method
  Future<AcceptFriendRequestUsecaseOutput> acceptFriendRequest(
      AcceptFriendRequestUsecaseInput input);

  /// [GetAllFriendsUsecaseInput] is received to [getAllFriends] method as parameter
  /// [GetAllFriendsUsecaseOutput] is returned from [getAllFriends] method
  GetAllFriendsUsecaseOutput getAllFriends(GetAllFriendsUsecaseInput input);

  /// [UnFriendUsecaseInput] is received to [unFriend] method as parameter
  /// [UnFriendUsecaseOutput] is returned from [unFriend] method
  Future<UnFriendUsecaseOutput> unFriend(UnFriendUsecaseInput input);

  /// [GetCloseFriendsUsecaseInput] is received to [getCloseFriends] method as parameter
  /// [GetCloseFriendsUsecaseOutput] is returned from [getCloseFriends] method
  GetCloseFriendsUsecaseOutput getCloseFriends(
      GetCloseFriendsUsecaseInput input);

  /// [AddFriendToCloseFriendUsecaseInput] is received to [addFriendToCloseFriend] method as parameter
  /// [AddFriendToCloseFriendUsecaseOutput] is returned from [addFriendToCloseFriend] method
  Future<AddFriendToCloseFriendUsecaseOutput> addFriendToCloseFriend(
      AddFriendToCloseFriendUsecaseInput input);


  /// [RemoveFriendFromCloseFriendsUsecaseInput] is received to [removeFriendFromCloseFriends] method as parameter
  /// [RemoveFriendFromCloseFriendsUsecaseOutput] is returned from [removeFriendFromCloseFriends] method
  Future<RemoveFriendFromCloseFriendsUsecaseOutput> removeFriendFromCloseFriends(RemoveFriendFromCloseFriendsUsecaseInput input);


  /// [CancelFriendRequestUsecaseInput] is received to [cancelFriendRequest] method as parameter
  /// [CancelFriendRequestUsecaseOutput] is returned from [cancelFriendRequest] method
  Future<CancelFriendRequestUsecaseOutput> cancelFriendRequest(CancelFriendRequestUsecaseInput input);

////********** END METHODS **********////
}
