////********** AUTOGENERATED FILE: DO NOT REMOVE ANY COMMENT IN THIS STYLE **********////
////********** START IMPORTS **********////
import 'package:hive_flutter/hive_flutter.dart';
import 'package:injectable/injectable.dart';
import 'package:logger/logger.dart';
import '../../../../../helpers/persistence/persistence_helper.dart';
import '../../../domain/usecases/save_contacts.dart';
import 'friends_local_datasource.dart';
import '../../../domain/usecases/remove_contacts.dart';
import '../../../domain/usecases/get_contacts.dart';
import '../../../domain/usecases/load_contacts.dart';
////********** END IMPORTS **********////

@LazySingleton(as: FriendsLocalDataSource)
class FriendsLocalDataSourceImp implements FriendsLocalDataSource {
  final Logger _logger;
  final PersistenceHelper _persistenceHelper;

  FriendsLocalDataSourceImp({
    required Logger logger,
    required PersistenceHelper persistenceHelper,
  })  : _logger = logger,
        _persistenceHelper = persistenceHelper;

////********** START METHODS **********////
  @override
  Future<SaveContactsUsecaseOutput> saveContacts(
      SaveContactsUsecaseInput input) async {
    final contactBox = await Hive.openBox('contacts');
    await contactBox.clear();
    await contactBox.addAll(input.numbers);
    return SaveContactsUsecaseOutput();
  }

  /// [RemoveContactsUsecaseInput] is received to [removeContacts] method as parameter
  /// [RemoveContactsUsecaseOutput] is returned from [removeContacts] method
  @override
  Future<RemoveContactsUsecaseOutput> removeContacts(
      RemoveContactsUsecaseInput input) async {
    final contactBox = await Hive.openBox('contacts');
    await contactBox.clear();
    return RemoveContactsUsecaseOutput();
  }

  /// [GetContactsUsecaseInput] is received to [getContacts] method as parameter
  /// [GetContactsUsecaseOutput] is returned from [getContacts] method
  @override
  Future<LoadContactsUsecaseOutput> loadContacts(
      LoadContactsUsecaseInput input) async {
    final contactBox = await Hive.openBox('contacts');
    final listOfPhones = <String>[
      for (final contact in contactBox.values) contact as String,
    ];

    return LoadContactsUsecaseOutput(
      numbers: listOfPhones,
    );
  }

////********** END METHODS **********////
}
