////********** AUTOGENERATED FILE: DO NOT REMOVE ANY COMMENT IN THIS STYLE **********////
////********** START IMPORTS **********////
import '../../../../../infrastructure/datasource.dart';
import '../../../domain/usecases/save_contacts.dart';
import '../../../domain/usecases/remove_contacts.dart';
import '../../../domain/usecases/load_contacts.dart';
////********** END IMPORTS **********////

abstract class FriendsLocalDataSource extends DataSource {
  ////********** START METHODS **********////
  /// [SaveContactsUsecaseInput] is received to [saveContacts] method as parameter
  /// [SaveContactsUsecaseOutput] is returned from [saveContacts] method
  Future<SaveContactsUsecaseOutput> saveContacts(
      SaveContactsUsecaseInput input);

  /// [RemoveContactsUsecaseInput] is received to [removeContacts] method as parameter
  /// [RemoveContactsUsecaseOutput] is returned from [removeContacts] method
  Future<RemoveContactsUsecaseOutput> removeContacts(
      RemoveContactsUsecaseInput input);

  /// [LoadContactsUsecaseInput] is received to [loadContacts] method as parameter
  /// [LoadContactsUsecaseOutput] is returned from [loadContacts] method
  Future<LoadContactsUsecaseOutput> loadContacts(
      LoadContactsUsecaseInput input);

////********** END METHODS **********////
}
