////********** AUTOGENERATED FILE: DO NOT REMOVE ANY COMMENT IN THIS STYLE **********////
////********** START IMPORTS **********////
import '../../../../../infrastructure/datasource.dart';
import '../../../domain/usecases/send_otp.dart';
import '../../../domain/usecases/verify_otp.dart';
import '../../../domain/usecases/get_user.dart';
import '../../../domain/usecases/update_user.dart';
import '../../../domain/usecases/switch_user_visibility.dart';
import '../../../domain/usecases/get_user_socket.dart';
////********** END IMPORTS **********////

abstract class AuthFirebaseDataSource extends DataSource {
  ////********** START METHODS **********////
  /// [SendOtpUsecaseInput] is received to [sendOtp] method as parameter
  /// [SendOtpUsecaseOutput] is returned from [sendOtp] method
  Future<SendOtpUsecaseOutput> sendOtp(SendOtpUsecaseInput input);


  /// [VerifyOtpUsecaseInput] is received to [verifyOtp] method as parameter
  /// [VerifyOtpUsecaseOutput] is returned from [verifyOtp] method
  Future<VerifyOtpUsecaseOutput> verifyOtp(VerifyOtpUsecaseInput input);


  /// [GetUserUsecaseInput] is received to [getUser] method as parameter
  /// [GetUserUsecaseOutput] is returned from [getUser] method
  Future<GetUserUsecaseOutput> getUser(GetUserUsecaseInput input);


  /// [UpdateUserUsecaseInput] is received to [updateUser] method as parameter
  /// [UpdateUserUsecaseOutput] is returned from [updateUser] method
  Future<UpdateUserUsecaseOutput> updateUser(UpdateUserUsecaseInput input);


  /// [SwitchUserVisibilityUsecaseInput] is received to [switchUserVisibility] method as parameter
  /// [SwitchUserVisibilityUsecaseOutput] is returned from [switchUserVisibility] method
  Future<SwitchUserVisibilityUsecaseOutput> switchUserVisibility(SwitchUserVisibilityUsecaseInput input);


  /// [GetUserSocketUsecaseInput] is received to [getUserSocket] method as parameter
  /// [GetUserSocketUsecaseOutput] is returned from [getUserSocket] method
  GetUserSocketUsecaseOutput getUserSocket(GetUserSocketUsecaseInput input);

////********** END METHODS **********////
}
  
