////********** AUTOGENERATED FILE: DO NOT REMOVE ANY COMMENT IN THIS STYLE **********////
////********** START IMPORTS **********////
import '../../../../../infrastructure/datasource.dart';
import '../../../domain/usecases/load_all_coutries.dart';
////********** END IMPORTS **********////

abstract class AuthAssetsDataSource extends DataSource {
  ////********** START METHODS **********////
  /// [LoadAllCoutriesUsecaseInput] is received to [loadAllCoutries] method as parameter
  /// [LoadAllCoutriesUsecaseOutput] is returned from [loadAllCoutries] method
  Future<LoadAllCoutriesUsecaseOutput> loadAllCoutries(LoadAllCoutriesUsecaseInput input);

////********** END METHODS **********////
}
  