////********** AUTOGENERATED FILE: DO NOT REMOVE ANY COMMENT IN THIS STYLE **********////
////********** START IMPORTS **********////
import 'auth_repository.dart';
import 'package:injectable/injectable.dart';
import '../../data/source/firebase/auth_firebase_datasource.dart';
import '../usecases/send_otp.dart';
import '../usecases/verify_otp.dart';
import '../usecases/get_user.dart';
import '../usecases/update_user.dart';
import '../../data/source/local/auth_local_datasource.dart';
import '../usecases/save_auth.dart';
import '../usecases/remove_auth.dart';
import '../usecases/check_auth.dart';
import '../../data/source/assets/auth_assets_datasource.dart';
import '../usecases/load_all_coutries.dart';
import '../usecases/switch_user_visibility.dart';
import '../usecases/get_user_socket.dart';
////********** END IMPORTS **********////

@LazySingleton(as: AuthRepository)
class AuthRepositoryImp implements AuthRepository {
////********** START VARIABLES **********////
  final AuthFirebaseDataSource _authFirebaseDataSource;
  final AuthLocalDataSource _authLocalDataSource;
  final AuthAssetsDataSource _authAssetsDataSource;

////********** END VARIABLES **********////

  AuthRepositoryImp({
////********** START RECEIVE VALUES **********////
    required AuthFirebaseDataSource authFirebaseDataSource,
    required AuthLocalDataSource authLocalDataSource,
    required AuthAssetsDataSource authAssetsDataSource,
////********** END RECEIVE VALUES **********////
  })  :
////********** START SET VALUES **********////
        _authFirebaseDataSource = authFirebaseDataSource,
        _authLocalDataSource = authLocalDataSource,
        _authAssetsDataSource = authAssetsDataSource
////********** END SET VALUES **********////
  ;

////********** START METHODS **********////
  /// [SendOtpUsecaseInput] is received to [sendOtp] method as parameter
  /// [SendOtpUsecaseOutput] is returned from [sendOtp] method
  @override
  Future<SendOtpUsecaseOutput> sendOtp(SendOtpUsecaseInput input) async {
    return _authFirebaseDataSource.sendOtp(input);
  }

  /// [VerifyOtpUsecaseInput] is received to [verifyOtp] method as parameter
  /// [VerifyOtpUsecaseOutput] is returned from [verifyOtp] method
  @override
  Future<VerifyOtpUsecaseOutput> verifyOtp(VerifyOtpUsecaseInput input) async {
    return _authFirebaseDataSource.verifyOtp(input);
  }

  /// [GetUserUsecaseInput] is received to [getUser] method as parameter
  /// [GetUserUsecaseOutput] is returned from [getUser] method
  @override
  Future<GetUserUsecaseOutput> getUser(GetUserUsecaseInput input) async {
    return _authFirebaseDataSource.getUser(input);
  }

  /// [UpdateUserUsecaseInput] is received to [updateUser] method as parameter
  /// [UpdateUserUsecaseOutput] is returned from [updateUser] method
  @override
  Future<UpdateUserUsecaseOutput> updateUser(
      UpdateUserUsecaseInput input) async {
    return _authFirebaseDataSource.updateUser(input);
  }

  /// [SaveAuthUsecaseInput] is received to [saveAuth] method as parameter
  /// [SaveAuthUsecaseOutput] is returned from [saveAuth] method
  @override
  Future<SaveAuthUsecaseOutput> saveAuth(SaveAuthUsecaseInput input) async {
    return _authLocalDataSource.saveAuth(input);
  }

  /// [RemoveAuthUsecaseInput] is received to [removeAuth] method as parameter
  /// [RemoveAuthUsecaseOutput] is returned from [removeAuth] method
  @override
  Future<RemoveAuthUsecaseOutput> removeAuth(
      RemoveAuthUsecaseInput input) async {
    return _authLocalDataSource.removeAuth(input);
  }

  /// [CheckAuthUsecaseInput] is received to [checkAuth] method as parameter
  /// [CheckAuthUsecaseOutput] is returned from [checkAuth] method
  @override
  Future<CheckAuthUsecaseOutput> checkAuth(CheckAuthUsecaseInput input) async {
    return _authLocalDataSource.checkAuth(input);
  }

  /// [LoadAllCoutriesUsecaseInput] is received to [loadAllCoutries] method as parameter
  /// [LoadAllCoutriesUsecaseOutput] is returned from [loadAllCoutries] method
  @override
  Future<LoadAllCoutriesUsecaseOutput> loadAllCoutries(
      LoadAllCoutriesUsecaseInput input) async {
    return _authAssetsDataSource.loadAllCoutries(input);
  }

  /// [SwitchUserVisibilityUsecaseInput] is received to [switchUserVisibility] method as parameter
  /// [SwitchUserVisibilityUsecaseOutput] is returned from [switchUserVisibility] method
  @override
  Future<SwitchUserVisibilityUsecaseOutput> switchUserVisibility(
      SwitchUserVisibilityUsecaseInput input) async {
    return _authFirebaseDataSource.switchUserVisibility(input);
  }

  /// [GetUserSocketUsecaseInput] is received to [getUserSocket] method as parameter
  /// [GetUserSocketUsecaseOutput] is returned from [getUserSocket] method
  @override
  GetUserSocketUsecaseOutput getUserSocket(GetUserSocketUsecaseInput input) {
    return _authFirebaseDataSource.getUserSocket(input);
  }

////********** END METHODS **********////
}
