////********** AUTOGENERATED FILE: DO NOT REMOVE ANY COMMENT IN THIS STYLE **********////
////********** START IMPORTS **********////
import 'package:injectable/injectable.dart';
import 'package:logger/logger.dart';
import '../../../../../helpers/persistence/persistence_helper.dart';
import '../../../domain/usecases/save_auth.dart';
import 'auth_local_datasource.dart';
import '../../../domain/usecases/remove_auth.dart';
import '../../../domain/usecases/check_auth.dart';
////********** END IMPORTS **********////

@LazySingleton(as: AuthLocalDataSource)
class AuthLocalDataSourceImp implements AuthLocalDataSource {
  final Logger _logger;
  final PersistenceHelper _persistenceHelper;

  AuthLocalDataSourceImp({
    required Logger logger,
    required PersistenceHelper persistenceHelper,
  })  : _logger = logger,
        _persistenceHelper = persistenceHelper;

////********** START METHODS **********////
  @override
  Future<SaveAuthUsecaseOutput> saveAuth(SaveAuthUsecaseInput input) async {
    await _persistenceHelper.saveString('user_id', input.id);
    return SaveAuthUsecaseOutput();
  }

  /// [RemoveAuthUsecaseInput] is received to [removeAuth] method as parameter
  /// [RemoveAuthUsecaseOutput] is returned from [removeAuth] method
  @override
  Future<RemoveAuthUsecaseOutput> removeAuth(
      RemoveAuthUsecaseInput input) async {
    await _persistenceHelper.delete('user_id');
    return RemoveAuthUsecaseOutput();
  }

  /// [CheckAuthUsecaseInput] is received to [checkAuth] method as parameter
  /// [CheckAuthUsecaseOutput] is returned from [checkAuth] method
  @override
  Future<CheckAuthUsecaseOutput> checkAuth(CheckAuthUsecaseInput input) async {
    final userId = await _persistenceHelper.getString('user_id');
    return CheckAuthUsecaseOutput(userId: userId);
  }

////********** END METHODS **********////
}
